### PR TITLE
Add missing error handling

### PR DESCRIPTION
**Pull request by MartinWeindel**
**What this PR does / why we need it**:
Add missing error handling on loading string map from record file as it can cause panic later on.

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Add missing error handling on loading string map from record file.
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Comment by axel7born** [comment]
Just out of curiosity: What is the reason for the change in `.reuse/dep5` and how is it generated?

**Comment by MartinWeindel** [comment]
@axel7born To check the reuse compliance of the listed licenses, the command line `pipx run reuse lint` is run. This tool performs automatic updates of the tools used internally. With the last update, multiple copyright lines are not allowed anymore for an entry. Therefore I had to merge them in single lines. At the moment there is no tool to generate the `.reuse/dep5` automatically 😞  It is manual effort.

**Pull request merged**
